### ISSUE TITLE
Using RTNeural instead of custom models?

### ISSUE THREAD

**Issue by baptistejamin** [sdatkinson/NeuralAmpModelerCore#113]
Hey Steven.

Thank you for building NAM.

RTNeural provides efficient kernels and activations, and NAM could simplify its processing by using it.

Do you think it is worth implementing it?

I see several advantages to this, such as significantly better performance, which allows the implementation of NAM with embedded devices.

It could also be possible to train models with multiple channels, allowing to train using different knobs, like Gain, or simulate fuzz pedals using different knobs

**Comment by sdatkinson** [comment]
Hi!

It sounds like that's an option, but it's out of scope for this repo (instead, it sounds like a completely new project), and may be for the RTNeural repo as well (it looks like it's not in-scope to maintain recipes for pre-defined architectures, based on my understanding of https://github.com/jatinchowdhury18/RTNeural/issues/143).

But if you would like to run NAMs using RTNeural's engine (and share it), then that seems to be open to do :)
