### ISSUE TITLE
Separate core NAM network code

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerCore#12]
In order to make the core NAM network code more portable, it would be good to separate it from the other plugin dsp code (noise gate, EQ, impulse response).

I propose a separate source directory for the actual NN code ("NAM"?) and separation of the existing code in dsp.h (it currently has two DSP class implementations - one for the network code and another for the other dsp functions).

If this seems good to you, I'll put together a quick PR for it.

**Comment by mikeoliphant** [comment]
I went ahead and submitted a PR:

**Comment by mikeoliphant** [comment]
I went ahead and submitted a PR:

https://github.com/sdatkinson/NeuralAmpModelerCore/pull/13

**Comment by mikeoliphant** [comment]
@sdatkinson @olilarkin - I would *really* like to get this sorted asap.

My PR (https://github.com/sdatkinson/NeuralAmpModelerCore/pull/13) now has conflicts - not sure how difficult they are to resolve.

Oli's PR (https://github.com/sdatkinson/NeuralAmpModelerCore/pull/15) does part of this (removes IPlug dependency, but doesn't separate the dsp.cpp/dsp.h code).

How do we move forward on this?

**Comment by olilarkin** [comment]
Could you make a follow-up piano on top of mine doing the extra changes
that you want?

**Comment by olilarkin** [comment]
Piano should be PR, obviously, stupid dictation

**Comment by mikeoliphant** [comment]
Yes - although there are a couple of open questions:

- Sample format - double, float, or maybe both (using preprocessor directive or template classes).
- Should the other dsp classes be de-iplugified at all? Or maybe moved back to the plugin repo?
