### ISSUE TITLE
Reduce input/output buffer copies in model processing

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerCore#27]
Currently, there are at least two buffer copies (one at input and one at output) that could be avoided by directly using the passed in input/output buffers.

**Comment by olilarkin** [comment]
I agree. The whole allocating arrays of raw input/output pointers stuff in both NeuralAmpModelerCore and the Plug-in code is very suspicious and probably the source of the memory leaks
