### ISSUE TITLE
Enable, or allow toggling, Fast Tanh

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerCore#30]
It would be great to get the fast tanh code out there - either by default, or as a toggle.

It drastically improves performance, and could do a lot to mitigate the high-CPU usage complaints people have.

PR https://github.com/sdatkinson/NeuralAmpModelerCore/pull/28 makes it very easy to integrate into the plugin.

**Comment by sdatkinson** [comment]
Whoa...I didn't realize they were _this_ close!

![image](https://user-images.githubusercontent.com/12240186/230748317-dcd46025-49b2-46b3-85bf-166837219498.png)

![image](https://user-images.githubusercontent.com/12240186/230748332-6c380602-f4d6-455a-8c6e-b40d7957a368.png)

**Comment by mikeoliphant** [comment]
Yeah - I just hardcoded it enabled in the LV2 plugin. I figure I'm *much* more likely to have people complain about CPU usage than any perceptible impact of the fast tanh.

It would be interesting to do a null test comparing the output of a model using normal vs tanh. The impact to the audio signal could be more or less than the error of the activation function - I don't have a good intuition which is more likely.

**Comment by sdatkinson** [comment]
> It would be interesting to do a null test comparing the output of a model using normal vs fast tanh

...which is what I was _literally_ doing before switching back over here haha

Seems great to me: Source signal: -16.5 LUFS integrated; Null test: -62.4 LUFS (-45.9 dB)

...Which is lower than nulling my Deluxe Reverb against itself (two reamps back to back).

Case closed 😄

**Comment by mikeoliphant** [comment]
Cool - I figured that would probably be the case, but it is good to have actual confirmation.
