### ISSUE TITLE
CI: Test loading and running various models

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerCore#47]
Thanks to #34 it's possible to build some tools automatically 🎉 

Next step would be to try running them with some models (LSTM, WaveNet, ConvNet).

Some super-light models should do--the goal I have with this Issue is to be able to assert correct operation--so we can be more confident as we iterate on the core code that we're not breaking models, etc.

**Comment by mikeoliphant** [comment]
Yeah - my thought was that we could have a few simple reference models and a reference signal. If we keep known "good" outputs for each model, we can do a test run at build time and ensure we are still getting correct output.
