### ISSUE TITLE
Missing virtual destructor in dsp class

### ISSUE THREAD

**Issue by maartentamminga** [sdatkinson/NeuralAmpModelerCore#62]
~DSP();
should be: 

  virtual ~DSP();

**Comment by sdatkinson** [comment]
Gotcha; this one?
https://github.com/sdatkinson/NeuralAmpModelerCore/blob/accaa16ef35bea2e3d257e5f15584f4f644f1438/dsp/dsp.h#L22

**Comment by maartentamminga** [comment]
yessir. Also, it would be good to add namespacing for all classes and methods in nam core. If one would use this in a larger codebase, this could become a problem
