### ISSUE TITLE
some IR files with uncommon subchunk1Size (>16) would fail to load

### ISSUE THREAD

**Issue by fab672000** [sdatkinson/NeuralAmpModelerCore#64]
the root cause is that the skipping and remainder code part has a bug:
   const int skipChars = extraBytes / 4 

should be:
    const int skipChars = extraBytes / 4 * 4; // truncate to dword size

Have a fix here:
https://github.com/sdatkinson/NeuralAmpModelerCore/pull/63

**Comment by falkTX** [comment]
why not use something like [dr_wav](https://github.com/mackron/dr_libs/blob/master/dr_wav.h) for handling these files? license is compatible, and it will handle all the cases we could possibly think of.
reading wav files has been a solved problem for many years, there is no need to do it all custom...

**Comment by fab672000** [comment]
> why not use something like [dr_wav](https://github.com/mackron/dr_libs/blob/master/dr_wav.h) for handling these files? license is compatible, and it will handle all the cases we could possibly think of. reading wav files has been a solved problem for many years, there is no need to do it all custom...

Could be interesting in future if there is enough needs to, but as of today ; I'm more towards one of the 5 principles of extreme programming: simplicity.

**Comment by sdatkinson** [comment]
Resolved by #63
