### ISSUE TITLE
Make core NAM interfaces mono

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerCore#77]
Along with the other cleanup of the core interfaces, I think it makes sense to consider making the model processing mono (rather than multi-channel).

There isn't any internal support for more than a single channel, and it would make the interface cleaner.

**Comment by sdatkinson** [comment]
Great suggestion. I like it.

**Comment by mikeoliphant** [comment]
It also has the benefit of making https://github.com/sdatkinson/NeuralAmpModelerCore/issues/27 much simpler to resolve.

**Comment by mikeoliphant** [comment]
Btw, I'd be happy to do a PR for this and https://github.com/sdatkinson/NeuralAmpModelerCore/issues/27, along with removing the input/output gain. No worries if you'd rather do it yourself, though.

**Comment by sdatkinson** [comment]
Go for it! 🙂
