### ISSUE TITLE
Remove constructors with loudness

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerCore#86]
These result in a lot of copied code. Instead, we can `->SetLoudness()` once at the end of [`get_dsp()`](https://github.com/sdatkinson/NeuralAmpModelerCore/blob/29c52545251a2deca65faa397fef815bf54ddfa7/NAM/get_dsp.cpp#L130C6-L130C6).

**Comment by mikeoliphant** [comment]
👍

This has bugged me since the loudness was added...

**Comment by sdatkinson** [comment]
Yeah, apologies for this.

I know _what_ higher-order function I want conceptually, but I'm way behind in my C++ compared to how I know how to do it in other languages 😅 (which is my general excuse for a lot of the kludges in this whole project's code!)

But this'll work better than current, which is at least something 🙂
